---
- hosts: win
  #tasks:
    #- name: "18.1.1 (L1) Ensure 'Enable screen saver' is set to 'Enabled'"
      #win_regedit:
              #path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
              #name: "NoLockScreenCamera"
              #data: "1"
              #type: dword