---
- hosts: win
  tasks:
    - name: "2.3.1.2 (L1) Ensure Accounts: Block Microsoft accounts is set to Users can't add or log on with Microsoft accounts"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "NoConnectedUser"
              data: "1"
              type: dword
    - name: "2.3.1.4 (L1) Ensure Accounts: Limit local account use of blank passwords to console logon only' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "LimitBlankPasswordUse"
              data: "1"
              type: dword
    - name: "2.3.2.1 (L1) Ensure 'Audit: Force audit policy subcategory settings (Windows Vista or later) to override audit policy category settings' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "SCENoApplyLegacyAuditPolicy"
              data: "1"
              type: dword
    - name: "2.3.2.2 (L1) Ensure 'Audit: Shut down system immediately if unable to log security audits' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "CrashOnAuditFail"
              data: "1"
              type: dword
    - name: "2.3.4.1 (L1) Ensure 'Devices: Allowed to format and eject removable media' is set to 'Administrators'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
              name: "AllocateDASD"
              data: "0"
              type: dword
    - name: "2.3.4.2 (L1) Ensure 'Audit: Shut down system immediately if unable to log security audits' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers
              name: "AddPrinterDrivers"
              data: "1"
              type: dword
    - name: "2.3.6.1 (L1) Ensure 'Domain member: Digitally encrypt or sign secure channel data (always)' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
              name: "RequireSignOrSeal"
              data: "1"
              type: dword
    - name: "2.3.6.2 (L1) Ensure 'Domain member: Digitally encrypt secure channel data (when possible)' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
              name: "SealSecureChannel"
              data: "1"
              type: dword
    - name: "2.3.6.3 (L1) Ensure 'Domain member: Digitally sign secure channel data (when possible)' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
              name: "SignSecureChannel"
              data: "1"
              type: dword
    - name: "2.3.6.4 (L1) Ensure 'Domain member: Disable machine account password changes' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
              name: "DisablePasswordChange"
              data: "0"
              type: dword
    - name: "2.3.6.6 (L1) Ensure 'Domain member: Require strong (Windows 2000 or later) session key' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
              name: "RequireStrongKey"
              data: "1"
              type: dword
    - name: "2.3.7.1 (L1) Ensure 'Interactive logon: Do not display last user name' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "DontDisplayLastUserName"
              data: "1"
              type: dword
    - name: "2.3.7.2 (L1) Ensure 'Interactive logon: Do not require CTRL+ALT+DEL' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "DisableCAD"
              data: "0"
              type: dword
    - name: "2.3.7.3 (L1) Ensure 'Interactive logon: Machine inactivity limit' is set to '900 or fewer second(s), but not 0'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "InactivityTimeoutSecs"
              data: "900"
              type: dword
    - name: "2.3.7.4 (L1) Configure 'Interactive logon: Message text for users attempting to log on'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "LegalNoticeText"
              data: "Citrix Systems, Inc. and its subsidiaries computer systems are for the job related use of Citrix personnel only. All information herein is the property of Citrix and authorized employees have the right to monitor these systems at any time."
              type: string
    - name: "2.3.7.5 (L1) Configure 'Interactive logon: Message title for users attempting to log on'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "LegalNoticeCaption"
              data: "Logon notice:"
              type: string
    - name: "2.3.7.7 (L1) Ensure 'Interactive logon: Prompt user to change password before expiration' is set to 'between 5 and 14 days'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
              name: "PasswordExpiryWarning"
              data: "14"
              type: dword
    - name: "2.3.7.8 (L1) Ensure 'Interactive logon: Require Domain Controller Authentication to unlock workstation' is set to 'Enabled' (MS only)"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
              name: "ForceUnlockLogon"
              data: "1"
              type: dword
    - name: "2.3.7.9 (L1) Ensure 'Interactive logon: Smart card removal behavior' is set to 'Lock Workstation' or higher"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
              name: "ScRemoveOption"
              data: "1"
              type: string
    - name: "2.3.8.1 (L1) Ensure 'Microsoft network client: Digitally sign communications (always)' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
              name: "RequireSecuritySignature"
              data: "1"
              type: dword
    - name: "2.3.8.2 (L1) Ensure 'Microsoft network client: Digitally sign communications (if server agrees)' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
              name: "EnableSecuritySignature"
              data: "1"
              type: dword
    - name: "2.3.8.3 (L1) Ensure 'Microsoft network client: Send unencrypted password to third-party SMB servers' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
              name: "EnablePlainTextPassword"
              data: "0"
              type: dword
    - name: "2.3.9.1 (L1) Ensure 'Microsoft network server: Amount of idle time required before suspending session' is set to '15 or fewer minute(s), but not 0'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
              name: "AutoDisconnect"
              data: "15"
              type: dword
    - name: "2.3.9.2 (L1) Ensure 'Microsoft network server: Digitally sign communications (always)' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
              name: "RequireSecuritySignature"
              data: "1"
              type: dword
    - name: "2.3.9.3 (L1) Ensure 'Microsoft network server: Digitally sign communications (if client agrees)' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
              name: "EnableSecuritySignature"
              data: "1"
              type: dword
    - name: "2.3.9.4 (L1) Ensure 'Microsoft network server: Disconnect clients when logon hours expire' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
              name: "enableforcedlogoff"
              data: "1"
              type: dword
    - name: "2.3.9.5 (L1) Ensure 'Microsoft network server: Server SPN target name validation level' is set to 'Accept if provided by client' or higher (MS only)"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
              name: "SMBServerNameHardeningLevel"
              data: "1"
              type: dword          
    - name: "2.3.10.2 (L1) Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts' is set to 'Enabled' (MS only)"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "RestrictAnonymousSAM"
              data: "1"
              type: dword
    - name: "2.3.10.3 (L1) Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts and shares' is set to 'Enabled' (MS only)"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "RestrictAnonymous"
              data: "1"
              type: dword
    - name: "2.3.10.5 (L1) Ensure 'Network access: Let Everyone permissions apply to anonymous users' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "EveryoneIncludesAnonymous"
              data: "0"
              type: dword
    - name: "2.3.10.9 (L1) Ensure 'Network access: Restrict anonymous access to Named Pipes and Shares' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "RestrictNullSessAccess"
              data: "0"
              type: dword
    - name: "2.3.10.11 (L1) Ensure 'Network access: Sharing and security model for local accounts' is set to 'Classic - local users authenticate as themselves'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "ForceGuest"
              data: "0"
              type: dword
    - name: "2.3.11.1 (L1) Ensure 'Network security: Allow Local System to use computer identity for NTLM' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "UseMachineId"
              data: "1"
              type: dword
    - name: "2.3.11.2 (L1) Ensure 'Network security: Allow LocalSystem NULL session fallback' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "RestrictAnonymous"
              data: "1"
              type: dword
    - name: "2.3.11.3 (L1) Ensure 'Network Security: Allow PKU2U authentication requests to this computer to use online identities' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u
              name: "AllowOnlineID"
              data: "1"
              type: dword
    - name: "2.3.11.4 (L1) Ensure 'Network security: Configure encryption types allowed for Kerberos' is set to 'AES128_HMAC_SHA1, AES256_HMAC_SHA1, Future encryption types'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters
              name: "SupportedEncryptionTypes"
              data: "2147483640"
              type: dword
    - name: "2.3.11.5 (L1) Ensure 'Network security: Do not store LAN Manager hash value on next password change' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "NoLMHash"
              data: "1"
              type: dword
    - name: "2.3.11.7 (L1) Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "LmCompatibilityLevel"
              data: "5"
              type: dword
    - name: "2.3.11.7 (L1) Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
              name: "LmCompatibilityLevel"
              data: "5"
              type: dword
    - name: "2.3.11.8 (L1) Ensure 'Network security: LDAP client signing requirements' is set to 'Negotiate signing' or higher"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Services\LDAP
              name: "LDAPClientIntegrity"
              data: "1"
              type: dword
    - name: "2.3.11.9 (L1) Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) clients' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
              name: "NTLMMinClientSec"
              data: "537395200"
              type: dword
    - name: "2.3.11.10 (L1) Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) servers' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
              name: "NTLMMinServerSec"
              data: "537395200"
              type: dword  
    - name: "2.3.13.1 (L1) Ensure 'Shutdown: Allow system to be shut down without having to log on' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System:ShutdownWithoutLogon
              name: "ShutdownWithoutLogon"
              data: "1"
              type: dword
    - name: "2.3.15.1 (L1) Ensure 'System objects: Require case insensitivity for non-Windows subsystems' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Kernel
              name: "ObCaseInsensitive"
              data: "1"
              type: dword      
    - name: "2.3.17.1 (L1) Ensure 'User Account Control: Admin Approval Mode for the Built-in Administrator account' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "FilterAdministratorToken"
              data: "1"
              type: dword
    - name: "2.3.17.2 (L1) Ensure 'User Account Control: Allow UIAccess applications to prompt for elevation without using the secure desktop' is set to 'Disabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "EnableUIADesktopToggle"
              data: "0"
              type: dword
    - name: "2.3.17.3 (L1) Ensure 'User Account Control: Behavior of the elevation prompt for administrators in Admin Approval Mode' is set to 'Prompt for consent on the secure desktop'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "ConsentPromptBehaviorAdmin"
              data: "2"
              type: dword
    - name: "2.3.17.4 (L1) Ensure 'User Account Control: Behavior of the elevation prompt for standard users' is set to 'Automatically deny elevation requests'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "ConsentPromptBehaviorUser"
              data: "0"
              type: dword 
    - name: "2.3.17.5 (L1) Ensure 'User Account Control: Detect application installations and prompt for elevation' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "EnableInstallerDetection"
              data: "1"
              type: dword
    - name: "2.3.17.6 (L1) Ensure 'User Account Control: Only elevate UIAccess applications that are installed in secure locations' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "EnableSecureUIAPaths"
              data: "1"
              type: dword 
    - name: "2.3.17.7 (L1) Ensure 'User Account Control: Run all administrators in Admin Approval Mode' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "EnableLUA"
              data: "1"
              type: dword  
    - name: "2.3.17.8 (L1) Ensure 'User Account Control: Switch to the secure desktop when prompting for elevation' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "PromptOnSecureDesktop"
              data: "1"
              type: dword      
    - name: "2.3.17.9 (L1) Ensure 'User Account Control: Virtualize file and registry write failures to per-user locations' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
              name: "EnableVirtualization"
              data: "1"
              type: dword                                     
